name: Auto-create new tags

on:
  push:
    branches:
      - master
      - main

jobs:
  tag-action:
    uses: valitydev/base-workflows/.github/workflows/auto-tag.yml@v1
    with:
      disable-additional-tags: true
