name: mvnotify

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

env:
  GROUP_ID: dev/vality/

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download packages from Maven Central
        run: |
          wget \
            -q \
            --user-agent=Mozilla/5.0 \
            -e robots=off \
            -r \
            -p \
            --no-parent \
            -A pom \
            https://repo.maven.apache.org/maven2/${{ env.GROUP_ID }}
      - name: Get new package tree
        run: |
          tree \
            --noreport \
            --sort=version \
            repo.maven.apache.org/maven2/${{ env.GROUP_ID }} > package-tree-new
      - name: Cache package tree
        id: cache-package-tree
        uses: actions/cache@v4
        with:
          path: package-tree-old
          key: ${{ runner.os }}-package-tree-${{ hashFiles('**/package-tree-new') }}
          restore-keys: |
            ${{ runner.os }}-package-tree-
      - name: Get and format diff
        if: steps.cache-package-tree.outputs.cache-hit == 'false'
        id: get-diff
        run: |
          DIFF=$(
              diff \
                -u \
                package-tree-old package-tree-new | \
                sed 1,2d | \
                sed '$!s/$/\\n/' | \
                tr -d '\n' || :
          )
          echo "diff-message=$DIFF" >> $GITHUB_OUTPUT
      - name: Get latest tag
        if: steps.get-diff.outputs.diff-message != ''
        id: latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
      - name: Create the Mattermost Message
        if: steps.get-diff.outputs.diff-message != ''
        run: |
          cat <<EOF > mattermost.json
          {
            "attachments": [
              {
                "title": "New packages has been deployed to Maven Central:",
                "text": "\`\`\`diff\n${{ steps.get-diff.outputs.diff-message }}\n\`\`\`",
                "footer_icon": "${{ secrets.MATTERMOST_ICON }}",
                "footer": "mvnotify ${{ steps.latest-tag.outputs.tag }}"
              }
            ]
          }
          EOF
      - name: Send message to Mattermost
        if: steps.get-diff.outputs.diff-message != ''
        uses: mattermost/action-mattermost-notify@1.1.0
        env:
          MATTERMOST_USERNAME: mvnotify
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: ${{ secrets.MATTERMOST_CHANNEL }}
          MATTERMOST_ICON: ${{ secrets.MATTERMOST_ICON }}
      - name: Set package-tree
        run: mv package-tree-new package-tree-old
