name: mvnotify

on:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'

env:
  GROUP_ID: dev/vality/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Cache package tree
      #   id: cache-package-tree
      #   uses: actions/cache@v2
      #   with:
      #     path: package-tree-old
      #     key: ${{ runner.os }}-package-tree
      # - name: Download packages from Maven Central
      #   run: wget --user-agent=Mozilla/5.0 -e robots=off -r -p --no-parent -A pom https://repo.maven.apache.org/maven2/${{ env.GROUP_ID }}
      # - name: Get new package tree
      #   run: tree -d --noreport repo.maven.apache.org/maven2/${{ env.GROUP_ID }} > package-tree-new
      - name: Get diff
        id: get-diff
        # if: steps.cache-package-tree.outputs.cache-hit == 'true'
        shell: bash
        run: |
          DIFF_RESULT = $(diff -u package-tree-old package-tree-new)
          if [-n $DIFF_RESULT]; then DIFF_RESULT = $(echo '$DIFF_RESULT' | sed 1,2d | grep '^[+-]' | sed '$!s/$/\\n/' | tr -d '\n'); fi
          echo "::set-output name=diff-result::DIFF_RESULT"
      - name: Format output
        id: format-output
        if: steps.get-diff.outputs.diff-result != ''
        run: echo '${{ steps.get-diff.outputs.diff-result }}'
      - name: Create the Mattermost Message
        if: steps.format-output.outputs.diff-message != ''
        run: |
          echo "{\"text\": \"New packages has been deployed to Maven Central:\n```diff\n${{ steps.format-output.outputs.diff-message }}\n```\"}" > mattermost.json
      - name: Show Mattermost Message
        if: steps.format-output.outputs.diff-message != ''
        run: |
          cat mattermost.json
      # - name: Send message to Mettermost
      #   if: steps.format-output.outputs.diff-message != ''
      #   uses: mattermost/action-mattermost-notify@1.1.0
      #   env:
      #     MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      #     MATTERMOST_CHANNEL: test
      # - name: Set package-tree
      #   run: mv package-tree-new package-tree-old
